language: elixir

matrix:
  include:
    - otp_release: 20.0
      elixir: 1.7.0

script:
  - "MIX_ENV=test mix do deps.get, test && mix credo && mix coveralls.travis"
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
